<?php

namespace App\Filament\Resources\Permissions;

use App\Filament\Resources\Permissions\Pages\ListPermissions;
use App\Models\Permission;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

/**
 * Every permission the application knows about.
 *
 * Read-only on purpose. A permission exists because a policy asks about it, so
 * the list is generated by {@see \Database\Seeders\RolePermissionSeeder} from
 * the policies themselves — inventing one here would give a name nothing ever
 * checks. This screen is for seeing what the names are and who holds them.
 */
class PermissionResource extends Resource
{
    protected static ?string $model = Permission::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedKey;

    protected static string|\UnitEnum|null $navigationGroup = 'Settings';

    protected static ?int $navigationSort = 3;

    protected static ?string $recordTitleAttribute = 'name';

    public static function canCreate(): bool
    {
        return false;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('name')
            ->defaultGroup('group')
            ->columns([
                TextColumn::make('name')
                    ->searchable()
                    ->weight('semibold')
                    ->copyable()
                    ->description(fn (Permission $record) => $record->description),

                TextColumn::make('group')->badge()->color('gray')->sortable()->toggleable(),

                TextColumn::make('roles_count')
                    ->counts('roles')
                    ->label('Held by')
                    ->suffix(' roles')
                    ->alignEnd(),
            ])
            ->filters([
                SelectFilter::make('group')
                    ->options(fn () => Permission::query()
                        ->whereNotNull('group')
                        ->distinct()
                        ->orderBy('group')
                        ->pluck('group', 'group')
                        ->all()),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPermissions::route('/'),
        ];
    }
}
